name: Build QMK firmware
on: [push, workflow_dispatch]

jobs:

  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Disable git safe directory checks
        run : git config --global --add safe.directory '*'

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set matrix for build
        id: set-matrix
        #Gets all directories containing a .json file and adds the directory name to the 'keyboard' list
        run: echo "matrix={\"keyboard\":[$(echo `ls */*.json` | perl -pe 's/(\S*?)\/.*?\.json/"\1"/g' | perl -pe 's/ /,/g')]}" >> $GITHUB_OUTPUT


  build:
    needs: generate-matrix
    name: Build ${{ matrix.keyboard }}
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix)  }}

    env:
      NAMESPACE: ${{ github.actor }}_${{ matrix.keyboard }}


    steps:
      - name: Disable git safe directory checks
        run : git config --global --add safe.directory '*'

      - name: Checkout QMK
        uses: actions/checkout@v3
        with:
          repository: qmk/qmk_firmware
          submodules: recursive

      - name: Checkout userspace
        uses: actions/checkout@v3
        with:
          path: users/${{ github.actor }}
          
      - name: Copy keyboard files
        run : mkdir -p users/${{ env.NAMESPACE }} && cp users/${{ github.actor }}/${{ matrix.keyboard }}/* users/${{ env.NAMESPACE }}

      - name: Set correct userspace name in rules.mk
        run : echo "USER_NAME := ${{ env.NAMESPACE }}" >> users/${{ env.NAMESPACE }}/rules.mk

      - name: Build firmware
        run : qmk compile "users/${{ env.NAMESPACE }}/keymap.json" -j 0 -e TARGET=${{ env.NAMESPACE }}

      - name: Archive firmware
        uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: ${{ env.NAMESPACE }}
          path: |
            *.hex
            *.bin
            *.uf2